pipeline:
  name: CI-11556
  identifier: CI11556
  projectIdentifier: nitisha
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: CI11556Server
        repoName: scm/har/naman-test.git
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: K8Linux
              namespace: ci-delegate-prod-one
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "hello"
